import os
from dotenv import load_dotenv


load_dotenv()

MEMBER_ROLE_MANAGEMENT_SPREADSHEET_ID = os.getenv("MEMBER_ROLE_MANAGEMENT_SPREADSHEET_ID")
TERMINED_CERTIFICATE_TEMPLATE_DOCS_WITH_CPF_ID = os.getenv("TERMINED_CERTIFICATE_TEMPLATE_DOCS_WITH_CPF_ID")
TERMINED_CERTIFICATE_TEMPLATE_DOCS_NO_CPF_ID = os.getenv("TERMINED_CERTIFICATE_TEMPLATE_DOCS_NO_CPF_ID")