import os
from dotenv import load_dotenv


load_dotenv()

CANDIDATES_INFORMATION_SPREADSHEET_ID = os.getenv("CANDIDATES_INFORMATION_SPREADSHEET_ID")
INTERVIEW_TEMPLATE_DOCS_ID = os.getenv("INTERVIEW_TEMPLATE_DOCS_ID")
CURRENT_RECRUITMENT_PROCESS_INTERVIEW_FOLDER_ID = os.getenv("CURRENT_RECRUITMENT_PROCESS_INTERVIEW_FOLDER_ID")